services:
  ubuntu-vnc:
    build: .
    # ポート設定 (ホスト側:コンテナ側)
    ports:
      - "3390:3389" # RDP接続用 (任意)
    volumes:
      - chrome-profile:/data
      - .:/app
    shm_size: '2gb'

# データの永続化に使うDocker Volumeを定義
volumes:
  chrome-profile:
